import { Geist } from "next/font/google";
import { ThemeProvider } from "./contexts/theme-context"
// import { AuthProvider } from "./contexts/auth-context"
import { Toaster } from "@/components/ui/sonner"
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import "./styles/page.css"

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight:'400'
});

export const metadata = {
  title: "Quimex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geist.variable}`}>
      <ThemeProvider>
          {/* <AuthProvider> */}
          <Toaster />
            {children}
          {/* </AuthProvider> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
